Drone.create!([
  {name: "Betsy five", notes: "Needs new propellers", favorite: false, status: "flyable", user_id: 1},
  {name: "yes", notes: "yes", favorite: true, status: "flyable", user_id: 3},
  {name: "My First Drone", notes: "never", favorite: true, status: "flyable", user_id: 1},
  {name: "Betsy Two", notes: "The Second!", favorite: true, status: "trash", user_id: 1}
])
Location.create!([
  {name: "Bryes House", address: "524 W addison st", latitude: "41.948091", longitude: "-87.644804", flight_zone_status: "no_flight_zone"},
  {name: "Actualize", address: "215 W Ohio st chicago il", latitude: "41.892137", longitude: "-87.634821", flight_zone_status: "no_flight_zone"},
  {name: "Shabbona", address: "Shabbona Illinois", latitude: "41.768085", longitude: "-88.877031", flight_zone_status: "flight_zone"},
  {name: "Praire Park", address: "615 Ellwood Ave, DeKalb, IL 60115", latitude: "41.925823", longitude: "-88.761982", flight_zone_status: "no_flight_zone"},
  {name: "White House", address: "white house", latitude: "38.8977", longitude: "-77.036553", flight_zone_status: "no_flight_zone"},
  {name: "Sears Tower", address: "Sears Tower", latitude: "41.878876", longitude: "-87.635928", flight_zone_status: "no_flight_zone"},
  {name: "Malta", address: "Malta Illinois", latitude: "41.929221", longitude: "-88.862314", flight_zone_status: "flight_zone"}
])
LocationReview.create!([
  {summary: "great place to fly!", warning: "No Warnings", rating: 5, user_location_id: 1},
  {summary: "bad", warning: "good", rating: 3, user_location_id: 2},
  {summary: "bad", warning: "great", rating: 5, user_location_id: 2},
  {summary: "bad", warning: "great", rating: 5, user_location_id: 2},
  {summary: "good", warning: "good", rating: nil, user_location_id: 2},
  {summary: "yes", warning: "yes", rating: nil, user_location_id: 27},
  {summary: "no", warning: "no", rating: nil, user_location_id: 29},
  {summary: "Great place to fly", warning: "no warnings", rating: 5, user_location_id: 27},
  {summary: "good", warning: " bad ", rating: 5, user_location_id: 63},
  {summary: "haha", warning: "haha", rating: 2, user_location_id: 63},
  {summary: "hello", warning: "hello", rating: 4, user_location_id: 63},
  {summary: "great", warning: "great", rating: 4, user_location_id: 64},
  {summary: "great", warning: "great", rating: 5, user_location_id: 64},
  {summary: "hello", warning: "hello", rating: 5, user_location_id: 64},
  {summary: "aaa", warning: "aaa", rating: 3, user_location_id: 64}
])
User.create!([
  {name: "brye", email: "brye@gmail.com", password_digest: "$2a$10$CVLH63hTEFth9ZxucQx4NeNyynI4HdIH2UlBJs2WaXsCwH5vz92vW", admin: true},
  {name: "danielle", email: "danielle@gmail.com", password_digest: "$2a$10$b7MA2aFLLsOustcuak2BpOLaIU/aHEYF4BfTUTga4TPb0ETvs5YAu", admin: false},
  {name: "Mark", email: "mark@gmail.com", password_digest: "$2a$10$osFBina8YlES0yRFm6pLOOKwnl6PiHTDQCFiPDPwvU2xvFUs/dBs.", admin: false}
])
UserLocation.create!([
  {location_id: 14, user_id: 1, status: "to_visit"},
  {location_id: 14, user_id: 1, status: "visited"},
  {location_id: 13, user_id: 1, status: "visited"}
])
Weather.create!([
  {good_to_fly: false, wind_speed: 5, temperature: 90, visibility_miles: 4, max_gust_speed: 9, chance_of_precipitation: 3, cloud_cover: 15, wind_direction: "north_east", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 78, visibility_miles: 8, max_gust_speed: 8, chance_of_precipitation: 10, cloud_cover: 10, wind_direction: "north_east", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 78, visibility_miles: 8, max_gust_speed: 8, chance_of_precipitation: 10, cloud_cover: 10, wind_direction: "north_east", location_id: 1},
  {good_to_fly: true, wind_speed: 1, temperature: 88, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 32, cloud_cover: 10, wind_direction: "south", location_id: 1},
  {good_to_fly: false, wind_speed: 10, temperature: 78, visibility_miles: 8, max_gust_speed: 8, chance_of_precipitation: 100, cloud_cover: 10, wind_direction: "north_east", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 78, visibility_miles: 8, max_gust_speed: 8, chance_of_precipitation: 10, cloud_cover: 10, wind_direction: "north_east", location_id: 1},
  {good_to_fly: nil, wind_speed: 12, temperature: 75, visibility_miles: 6, max_gust_speed: 12, chance_of_precipitation: 50, cloud_cover: 50, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 40, visibility_miles: 6, max_gust_speed: 14, chance_of_precipitation: 60, cloud_cover: 50, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 99, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 42, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 10, temperature: 80, visibility_miles: 5, max_gust_speed: 12, chance_of_precipitation: 40, cloud_cover: 50, wind_direction: "north", location_id: 1},
  {good_to_fly: nil, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 99, temperature: 99, visibility_miles: 99, max_gust_speed: 99, chance_of_precipitation: 99, cloud_cover: 99, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 8, temperature: 8, visibility_miles: 8, max_gust_speed: 8, chance_of_precipitation: 8, cloud_cover: 8, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 88, temperature: 88, visibility_miles: 88, max_gust_speed: 88, chance_of_precipitation: 88, cloud_cover: 88, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 10, temperature: 50, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 30, cloud_cover: 50, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north", location_id: 1},
  {good_to_fly: false, wind_speed: 25, temperature: 99, visibility_miles: 1, max_gust_speed: 25, chance_of_precipitation: 60, cloud_cover: 90, wind_direction: "south", location_id: 2},
  {good_to_fly: false, wind_speed: 12, temperature: 12, visibility_miles: 12, max_gust_speed: 12, chance_of_precipitation: 12, cloud_cover: 12, wind_direction: "north", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 95, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "north_east", location_id: 1},
  {good_to_fly: true, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "south", location_id: 14},
  {good_to_fly: false, wind_speed: nil, temperature: nil, visibility_miles: nil, max_gust_speed: nil, chance_of_precipitation: nil, cloud_cover: nil, wind_direction: nil, location_id: 12},
  {good_to_fly: false, wind_speed: 3, temperature: 58, visibility_miles: 9, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: false, wind_speed: 3, temperature: 58, visibility_miles: 9, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 3, temperature: 58, visibility_miles: 9, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 13},
  {good_to_fly: false, wind_speed: 20, temperature: 35, visibility_miles: 10, max_gust_speed: 27, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: true, wind_speed: 13, temperature: 36, visibility_miles: 8, max_gust_speed: 19, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 13},
  {good_to_fly: false, wind_speed: 20, temperature: 36, visibility_miles: 10, max_gust_speed: 24, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: false, wind_speed: 13, temperature: 75, visibility_miles: 7, max_gust_speed: 25, chance_of_precipitation: 0, cloud_cover: 1, wind_direction: nil, location_id: 16},
  {good_to_fly: true, wind_speed: 11, temperature: 35, visibility_miles: 8, max_gust_speed: 20, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 10, temperature: 70, visibility_miles: 5, max_gust_speed: 10, chance_of_precipitation: 40, cloud_cover: 60, wind_direction: "west", location_id: 12},
  {good_to_fly: true, wind_speed: 11, temperature: 36, visibility_miles: 8, max_gust_speed: 20, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 11, temperature: 36, visibility_miles: 8, max_gust_speed: 20, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 6, temperature: 41, visibility_miles: 9, max_gust_speed: 10, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 4, temperature: 83, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 83, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 83, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 83, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 83, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 82, visibility_miles: 10, max_gust_speed: 10, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 1, temperature: 40, visibility_miles: 8, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 1, temperature: 40, visibility_miles: 8, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: false, wind_speed: 15, temperature: 39, visibility_miles: 9, max_gust_speed: 21, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: true, wind_speed: 5, temperature: 51, visibility_miles: 7, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 16},
  {good_to_fly: true, wind_speed: 1, temperature: 40, visibility_miles: 8, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 1, temperature: 40, visibility_miles: 8, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 1, temperature: 40, visibility_miles: 8, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 15, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 15, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 14, temperature: 41, visibility_miles: 9, max_gust_speed: 15, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 13, temperature: 41, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 13, temperature: 41, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 13, temperature: 41, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 13, temperature: 41, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 13, temperature: 41, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: true, wind_speed: 11, temperature: 38, visibility_miles: 8, max_gust_speed: 16, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: true, wind_speed: 5, temperature: 37, visibility_miles: 7, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 6, temperature: 78, visibility_miles: 10, max_gust_speed: 19, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 37, visibility_miles: 7, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 5, temperature: 36, visibility_miles: 7, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 5, temperature: 36, visibility_miles: 7, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 6, temperature: 74, visibility_miles: 10, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: false, wind_speed: 8, temperature: 31, visibility_miles: 9, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 15},
  {good_to_fly: false, wind_speed: 8, temperature: 30, visibility_miles: 9, max_gust_speed: 14, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: false, wind_speed: 8, temperature: 30, visibility_miles: 9, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 20},
  {good_to_fly: false, wind_speed: 10, temperature: 99, visibility_miles: 10, max_gust_speed: 13, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 9, temperature: 98, visibility_miles: 10, max_gust_speed: 12, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 9, temperature: 98, visibility_miles: 10, max_gust_speed: 12, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 8, temperature: 97, visibility_miles: 10, max_gust_speed: 10, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 87, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 87, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 87, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 87, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 87, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 86, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 85, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 84, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 84, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 84, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 84, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 81, visibility_miles: 10, max_gust_speed: 8, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 81, visibility_miles: 10, max_gust_speed: 8, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 81, visibility_miles: 10, max_gust_speed: 8, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 81, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 81, visibility_miles: 10, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 80, visibility_miles: 10, max_gust_speed: 10, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 80, visibility_miles: 10, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 80, visibility_miles: 10, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 80, visibility_miles: 10, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 78, visibility_miles: 10, max_gust_speed: 17, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 77, visibility_miles: 10, max_gust_speed: 17, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 77, visibility_miles: 10, max_gust_speed: 13, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 75, visibility_miles: 10, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 75, visibility_miles: 10, max_gust_speed: 11, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 3, temperature: 38, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 20},
  {good_to_fly: true, wind_speed: 5, temperature: 38, visibility_miles: 9, max_gust_speed: 7, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 12},
  {good_to_fly: true, wind_speed: 5, temperature: 83, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 83, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 9, temperature: 36, visibility_miles: 8, max_gust_speed: 9, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 35, visibility_miles: 9, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 35, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 6, temperature: 34, visibility_miles: 9, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 38, visibility_miles: 9, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 38, visibility_miles: 9, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 38, visibility_miles: 9, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 4, temperature: 38, visibility_miles: 9, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil},
  {good_to_fly: true, wind_speed: 5, temperature: 38, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: true, wind_speed: 5, temperature: 39, visibility_miles: 10, max_gust_speed: 5, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: 14},
  {good_to_fly: true, wind_speed: 5, temperature: 41, visibility_miles: 10, max_gust_speed: 6, chance_of_precipitation: 0, cloud_cover: 0, wind_direction: nil, location_id: nil}
])
